### PR TITLE
Add labelled square matrix samples

### PR DESCRIPTION
**Pull request by kdmurray91**
For BioJulia/Bio.jl#253

### CODE REVIEW

**Comment by bicycle1885** [comment]
Could you add [NUC4.4](ftp://ftp.ncbi.nih.gov/blast/matrices/NUC.4.4) and [BLOSUM62](ftp://ftp.ncbi.nih.gov/blast/matrices/BLOSUM62)? These will be used in `Bio.Align`.

**Comment by bicycle1885** [comment]
Here are the links:
* ftp://ftp.ncbi.nih.gov/blast/matrices/BLOSUM62
* ftp://ftp.ncbi.nih.gov/blast/matrices/NUC.4.4

**Comment by kdmurray91** [comment]
@bicycle1885 Done! Fixing tests now.

**Comment by bicycle1885** [comment]
Ah! you forget to add index.yml file in the LSM directory. Please see the [FASTA/index.yml](https://github.com/BioJulia/BioFmtSpecimens/blob/master/FASTA/index.yml) file as an example.

**Comment by kdmurray91** [comment]
@bicycle1885 like so?

**Comment by bicycle1885** [comment]
Looks good 👍 You can merge it now.

**Comment by kdmurray91** [comment]
Apparently not. while I now see merge buttons for the Bio.jl repo, I don't seem to have org/admin access to this repo. Weird.

**Comment by bicycle1885** [comment]
@kdmurray91 I guess you have now permission to merge pull requests. I don't know the system of GitHub organizations. I'm sorry for your inconvenience.

**Comment by Ward9250** [comment]
@kdmurray91 You are in the core dev team of BioJulia, which gives people admin access to all repo's related to code projects (which is currently almost all projects/repos, but may not be in the future as other BioJulia ventures such as web and educational resources are worked on), but BioFmtSpecimens was not included. I've changed this so as it is now, so all core dev members will be able to admin this repo.

**Comment by kdmurray91** [comment]
@Ward9250 & @bicycle1885  Thanks, and no worries! Merging now.

**Pull request merged**
