### PR TITLE
Remove the error that is no longer an error; replace with a real file from SCOPe

### PR DESCRIPTION
**Pull request by tanhevg**
See https://github.com/BioJulia/BioStructures.jl/pull/12

### CODE REVIEW

**Comment by jgreener64** [comment]
This is a useful additional file, thanks. Also, could you update the `index.yml` file?

As stated at the other PR, the 1SSU_err should stay as is.

**Comment by tanhevg** [comment]
> This is a useful additional file, thanks. Also, could you update the `index.yml` file?
> 
> As stated at the other PR, the 1SSU_err should stay as is.

Done

**Comment by jgreener64** [comment]
Okay this looks good to me. Could someone with write access please merge if they are happy?

**Comment by jgreener64** [comment]
Thanks Ben.

**Comment by BenJWard** [comment]
No problem!

**Pull request merged**
