### PR TITLE
Some mmCIF files (protein structures)

### PR DESCRIPTION
**Pull request by jgreener64**
I am working on a mmCIF parser for BioStructures.jl, so it would be good to have some mmCIF examples in this repo to test from.

Let me know if this needs anything else!

### CODE REVIEW

**Comment by Ward9250** [comment]
You could add some invalid files to see if the reader correctly throws if a bad file is provided to your reader, you can do that on this PR if you want or a future one. Once you've decided, I think this can go in.

**Comment by jgreener64** [comment]
Yes that's a good idea, have added some.

**Comment by Ward9250** [comment]
:+1: Awesome, this looks good.

**Comment by jgreener64** [comment]
Thanks for the merge. I guess the commit tag for `get_bio_fmt_specimens` in https://github.com/BioJulia/BioCore.jl/blob/master/src/Testing.jl has to be updated and a new release tagged for BioCore.jl?

This seems a hassle to do every time, could the default argument for `get_bio_fmt_specimens` just be `master`?

**Comment by Ward9250** [comment]
Good idea, I missed that in all the renovations. Rather than pull master blindly we could have it  get a latest tag, something like this: https://stackoverflow.com/questions/17414104/git-checkout-latest-tag so then we can start versioning BioFmtSpecimens.

**Comment by jgreener64** [comment]
Yes that's a good idea.

**Comment by Ward9250** [comment]
@jgreener64 https://github.com/BioJulia/BioCore.jl/pull/9 has a preview, it can be given a branch / tag / commit, but can by default just figure out the latest tag and use that. It also now has an override to force reinstallation - may be useful in some circumstances.

**Pull request merged**
